CREATE TABLE [dbo].[User]
(
	[Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[Email] NVARCHAR(386) NOT NULL,
	[Password] VARBINARY(64) NOT NULL,
	[Salt] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT [PK_User] PRIMARY KEY ([Id]),
	CONSTRAINT [UK_User_Email] UNIQUE ([Email])
)
